### PR TITLE
publish wheels

### PR DESCRIPTION
**Pull request by dimbleby**
- publish wheels as well as sdists
- direct invocation of `setup.py` is deprecated these days, prefer `build` to create those distributions
- fix the makefile so that it uses the virtual environment that it creates

### CODE REVIEW

**Comment by dimbleby** [comment]
(you might want to update your bot so that it points to something more useful than 404 not found)

**Comment by dimaqq** [comment]
Thank you @dimbleby 

May I ask the context for your request? Are you using this library or is this a generic concern?

P.S. I was going to improve the build and publication process, though I was thinking jump in the deep end, and go for uv and trusted publishing... That being said, I like simplicity of this PR.

I'll get back to this after #1186 where `pyproject.toml` is introduced and perhaps `setup.py` can be dropped.

**Comment by dimaqq** [comment]
WDYT about this: https://github.com/juju/python-libjuju/pull/1186/commits/cb4a962f99c9f265da2300380a7d04330ee2c904 inspired by your PR?

**Comment by dimbleby** [comment]
If you want to work in uv-world then I would simply replace `python -m build` with `uv build`.

Your commit leaves a virtualenv created but unused - though that is a side-issue.

I'm here not as a user but just someone trying to make the python ecosystem better, one project at a time...

**Comment by dimaqq** [comment]
Thank you @dimbleby , I didn't think `uv build` would work out of the box, but it does indeed!

Incorporated into https://github.com/juju/python-libjuju/pull/1186/commits/f5b93e79873f66907522800ce7d24db29fb4cd19

**Comment by dimaqq** [comment]
Closing this PR, as I've added `uv build` in #1186

**Comment by dimaqq** [comment]
Thank you for pointing me to the obvious!

**Pull request closed without merging**
