### PR TITLE
Merge master into 2.9

### PR DESCRIPTION
**Pull request by SimonRichardson**
Merge master into 2.9, this should bring all the new changes in master into 2.9

From there we should be able to cut a new release with charmhub support.

### CODE REVIEW

**Comment by hpidcock** [comment]
!!build!!

**Comment by cderici** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Review by cderici — APPROVED** [review]
All the unit tests are passing, we'll look into the integration failures in separate issues.

**Comment by SimonRichardson** [comment]
$$merge$$

**Pull request merged**
