### PR TITLE
Feature/ppa build

### PR DESCRIPTION
**Pull request by ycliuhw**
Add a way to build `python-libjuju` to a deb package;

### CODE REVIEW

**Comment by wallyworld** [comment]
I tested it - built the deb - and tried to install. There may be some dependency entries that are missing from the deb metadata:

```
$ sudo dpkg --instdir /tmp -i deb_dist/python3-juju_2.7.1-1_all.deb
Selecting previously unselected package python3-juju.
(Reading database ... 253274 files and directories currently installed.)
Preparing to unpack .../python3-juju_2.7.1-1_all.deb ...
Unpacking python3-juju (2.7.1-1) ...
dpkg: dependency problems prevent configuration of python3-juju:
 python3-juju depends on python3-macaroonbakery; however:
  Package python3-macaroonbakery is not installed.
 python3-juju depends on python3-paramiko; however:
  Package python3-paramiko is not installed.
 python3-juju depends on python3-pyasn1; however:
  Package python3-pyasn1 is not installed.
 python3-juju depends on python3-rfc3339; however:
  Package python3-rfc3339 is not installed.
 python3-juju depends on python3-toposort; however:
  Package python3-toposort is not installed.
 python3-juju depends on python3-websockets; however:
  Package python3-websockets is not installed.

dpkg: error processing package python3-juju (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 python3-juju

```

**Comment by AdamIsrael** [comment]
That's normal when installing a deb by hand. Run `apt-get -f install` to pull in the dependencies and finish configuring.

**Comment by ycliuhw** [comment]
!!build!!

**Comment by ycliuhw** [comment]
[package pylibjuju as a ppa](https://trello.com/c/HVOh59zY/1040-package-pylibjuju-as-a-ppa)

**Comment by ycliuhw** [comment]
$$merge$$

**Pull request merged**
