### PR TITLE
[JUJU-158] Add python3.9 to setup.py

### LINKED ISSUE #584: setup.py fails to reference support for python 3.9
https://github.com/juju/python-libjuju/blob/d6bb9183b7d1dc21a506fe72d43803fb61be40a3/setup.py#L61

### PR DESCRIPTION
**Pull request by cderici**
### Description

Fixes #584 

### QA Steps

```sh
N/A
```

### Notes & Discussion

### CODE REVIEW

**Review by SimonRichardson — APPROVED** [review]

**Comment by cderici** [comment]
$$merge$$

**Comment by cderici** [comment]
$$merge$$

**Comment by cderici** [comment]
!!build!!

**Comment by cderici** [comment]
$$merge$$

**Pull request merged**
