### PR TITLE
unify parse_storage_constraint or client.Constraints during deploy

### LINKED ISSUE #1075: Fail to deploy charm with storage parameter
### Description

Trying to update libjuju from 3.5.0.0 to 3.5.2.0 breaks tests setting the storage parameter during deploy. Example CI run can be seen [here](https://github.com/canonical/postgresql-operator/actions/runs/10001508952/job/27654326213?pr=531). Deploying a locally build charm with:
```
        await ops_test.model.deploy(
            charm,
            application_name=FIRST_APPLICATION,
            num_units=3,
            series=CHARM_SERIES,
            storage={"pgdata": {"pool": "lxd-btrfs", "size": 2048}},
            config={"profile": "testing"},
        )
```
Will result in:
```
  File "/home/runner/work/postgresql-operator/postgresql-operator/tests/integration/ha_tests/test_restore_cluster.py", line 40, in test_build_and_deploy
    await ops_test.model.deploy(
  File "/home/runner/work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/juju/model.py", line 1841, in deploy
    return await self._deploy(
  File "/home/runner/work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/juju/model.py", line 2154, in _deploy
    storage=***k: parse_storage_constraint(v) for k, v in (storage or dict()).items()***,
  File "/home/runner/work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/juju/model.py", line 2154, in <dictcomp>
    storage=***k: parse_storage_constraint(v) for k, v in (storage or dict()).items()***,
  File "/home/runner/work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/juju/constraints.py", line 131, in parse_storage_constraint
    for m in STORAGE.finditer(constraint):
TypeError: expected string or bytes-like object
```
Trying to deploy something like:
```
await model.deploy("postgresql", storage={"pgdata": "lxd-btrfs,1,2G"}, config={"profile": "testing"})
```
Fails different validation:
```
TypeError: juju.client._definitions.Constraints() argument after ** must be a mapping, not str
```

I think the issue is caused by the additional validation added in [model.py L2119](https://github.com/juju/python-libjuju/blob/main/juju/model.py#L2119)

### Urgency

Annoying bug in our test suite

### Python-libjuju version

3.5.2.0

### Juju version

3.4.4

### Reproduce / Test

```python
>>> import asyncio
>>> from juju.model import Model
>>> model = Model()
>>> await model.connect_current()
>>> await model.deploy("postgresql", storage={"pgdata": {"pool": "lxd-btrfs", "size": 2048}}, config={"profile": "testing"})
```

### PR DESCRIPTION
**Pull request by addyess**
#### Description

Fixes #1075 by collapsing both storage constraint deviations in `model._deploy`

#### QA Steps

```
tox -e integration -- tests/integration/test_model.py -k test_deploy_with_storage
```

All CI tests need to pass.

#### Notes & Discussion

Perhaps it's not the best change, feel free to scrap and adjust better.

### CODE REVIEW

**Comment by addyess** [comment]
@cderici do you think this is a PR that could be reviewed?

**Comment by dimaqq** [comment]
This PR needs to be rebased since #1186 has been merged.

**Comment by addyess** [comment]
@dimaqq any chance this PR can get a look now?

**Comment by dimaqq** [comment]
I've asked on Matrix for a review.

Meanwhile, please run pre-commit on your change.

**Comment by dimaqq** [comment]
I had a cursory look, the changes are in the `_deploy()` function.

It's used only twice, in Model's `deploy()` and bundle's `deploy()`.

Model's higher level function already coerces this argument, but maybe not correctly? that is it allows dicts but not strings.

I feel that this change needs to be refactored at the very least.

**Comment by addyess** [comment]
```sh
⚡ pre-commit run --files $(echo juju/client/_[cd]*.py) 
check for added large files..............................................Passed
check python ast.........................................................Passed
check for case conflicts.................................................Passed
check that executables have shebangs.................(no files to check)Skipped
check that scripts with shebangs are executable..........................Passed
check for merge conflicts................................................Passed
check for broken symlinks............................(no files to check)Skipped
check json...........................................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
check toml...........................................(no files to check)Skipped
mixed line ending........................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
detect private key.......................................................Passed
ruff.....................................................................Passed
ruff-format..............................................................Passed
codespell................................................................Passed
```

**Comment by addyess** [comment]
I wonder if this was actually already fixed by @james-garner-canonical  in #1105 in which case we could close this PR and the associated issue #1075

**Comment by james-garner-canonical** [comment]
Hi @addyess , it's plausible that #1105 did indeed fix #1075. It sounds like #1105 was fixing an error introduced in #1053, which was indeed released in [3.5.2.0](https://github.com/juju/python-libjuju/releases/tag/3.5.2.0) -- unfortunately #1105 wasn't linked to #1075 or your PR. I'll have to take a deeper look on Monday. Hopefully we can do a 3.5.2.2 release to get this fix to you.

**Comment by james-garner-canonical** [comment]
Should now be fully resolved in `main` by
- #1213

Thanks for your help with this, @adyess 

Release coming soon!

**Pull request closed without merging**
