### PR TITLE
[JUJU-2456] Fix compatibility with app facade version 6

### LINKED ISSUE #792: [Bug]: Nightly release edge testing is failing
### Description

It looks like somewhere around `juju 3.0.3` the `DestroyUnits` in `Application` facade disappears. And it causes the nightly edge to fail.

https://github.com/juju/python-libjuju/actions/runs/3944665126/jobs/6750814571

### Urgency

Casually reporting

### Python-libjuju version

edge

### Juju version

3.0.3-2c6b7fb

### Reproduce / Test

```python
The nightly release edge testing should be passing.

https://github.com/juju/python-libjuju/actions/workflows/test_edge.yaml
```

### PR DESCRIPTION
**Pull request by juanmanuel-tirado**
#### Description

Application facade was updated to version 16 and `DestroyUnits` function was renamed `DestroyUnit`

This fix #792 

#### QA Steps

Nightly build should pass.

#### Notes & Discussion

NA

### CODE REVIEW

**Review by cderici — CHANGES_REQUESTED** [review]
So I see two options to move forward here, 

1) safely move to `Application` facade `v16` *without* changing  `DestroyUnits -> DestroyUnit` (the test will pass after  https://github.com/juju/juju/pull/15077 lands), 
2) move further to `v17` and keep your change `DestroyUnits -> DestroyUnit` in which case we also need to get the new schema and regenerate the clients (after https://github.com/juju/juju/pull/15077 lands of course).

**Comment by juanmanuel-tirado** [comment]
We will have to go for the second option because we are promising to support the latest version.

**Comment by cderici** [comment]
> We will have to go for the second option because we are promising to support the latest version.

agreed.

**Comment by juanmanuel-tirado** [comment]
I will close this PR in favour of #791

**Pull request closed without merging**
