### PR TITLE
Update to latest juju 2.8.10 schema

### PR DESCRIPTION
**Pull request by SimonRichardson**

### CODE REVIEW

**Review by achilleasa — APPROVED** [review]
This should also fix #476.

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by johnsca** [comment]
Can we get this released to PyPI?  That's still on 2.8.5.

**Comment by SimonRichardson** [comment]
> Can we get this released to PyPI? That's still on 2.8.5.

Yeah, I was planning on doing it by end of this week.

**Pull request merged**
