### PR TITLE
Fixed the bundle run when the channel is None

### PR DESCRIPTION
**Pull request by oEscal**
Signed-off-by: Pedro Escaleira <pedroescaleira@hotmail.com>

Fix for issue #663

### CODE REVIEW

**Review by SimonRichardson — CHANGES_REQUESTED** [review]
This isn't correct for charmstore or local charms. You'll need to check for charmhub charms. Also, I'm surprised you need this at all.

**Comment by oEscal** [comment]
> This isn't correct for charmstore or local charms. You'll need to check for charmhub charms. Also, I'm surprised you need this at all.

For charms from the charm store is just "stable" the default channel?
Yes, I was also a bit surprised by this error, but as I have shown in the related issue, for that bundle, which supposedly is not specifying the version of mariadb, the said error was being thrown.

**Comment by SimonRichardson** [comment]
> For charms from the charm store is just "stable" the default channel?

Yes and empty for local charms

**Review by cderici — CHANGES_REQUESTED** [review]
Thanks for your work @oEscal! This lgtm in general. Let's fix the errors in the CI tests and land this soon. 

I'd also love to see a specific test for your change (to make sure we won't regress in the future).

**Comment by oEscal** [comment]
> Thanks for your work @oEscal! This lgtm in general. Let's fix the errors in the CI tests and land this soon.
> 
> I'd also love to see a specific test for your change (to make sure we won't regress in the future).

Thank you @cderici 
When I have the time, I will take a look into the tests, and fix them accordingly. I will also try to create some tests for this specific fix, as you mentioned.

**Comment by oEscal** [comment]
> @oEscal did you have any chance to take a look at this?

No, not yet, I have had a lot of work and was not able to take a look again into this. However, I hope to do so this next week. Sorry for the inconvenience.

**Comment by oEscal** [comment]
> > @oEscal did you have any chance to take a look at this?
> 
> No, not yet, I have had a lot of work and was not able to take a look again into this. However, I hope to do so this next week. Sorry for the inconvenience.

Ok, the week just passed, and I did not manage to have time to do so, and I don't know when I will have free time to do it (maybe two weeks from now). Is this something with high priority?

**Comment by cderici** [comment]
> Ok, the week just passed, and I did not manage to have time to do so, and I don't know when I will have free time to do it (maybe two weeks from now). Is this something with high priority? @cderici

Not the highest priority, but good to have as soon as possible. After all this is a fix for the issue you posted, and will unblock us to work on the other issue you posted (#662), so sooner it's resolved, sooner the changes will be in the next release :)

Thanks for following it up!

**Comment by oEscal** [comment]
@cderici I have fixed the unit test that was failing and created two new ones, to verify the changes made in this patch.

**Comment by juanmanuel-tirado** [comment]
Parts of the failing integration tests are not due to this contribution. I will merge it.

**Pull request merged**
