### PR TITLE
Allow switch kwarg in refresh to switch to local charms

### PR DESCRIPTION
**Pull request by jack-w-shaw**
Port forward https://github.com/juju/python-libjuju/pull/968

Check if the switch param is pointing to a local charm. If it is, run local_refresh as if it were provided

This is how the Juju CLI works, which was missing from pylibjuju. Replicate this.

Also push url parsing of switch kwarg behind a check if it's local charm, meaning we avoid the possibility where we attempt to parse a path as if it were a url

Resolves https://github.com/juju/python-libjuju/issues/963

### QA Steps

```
tox -e integration -- tests/integration/test_application.py::test_refresh_charmhub_to_local
```

All CI tests need to pass.

Verify the following example script runs successfully:
```
from juju import jasyncio
from juju.model import Model


async def main():
    model = Model()
    print('Connecting to model')
    await model.connect()
    try:
        print('path="/home/jack/charms/ubuntu"')
        await depl(model, path="/home/jack/charms/ubuntu")
        print('switch="/home/jack/charms/ubuntu"')
        await depl(model, switch="/home/jack/charms/ubuntu")
        print('switch="local:/home/jack/charms/ubuntu"')
        await depl(model, switch="local:/home/jack/charms/ubuntu")
    finally:
        print('Disconnecting from model')
        await model.disconnect()

async def depl(model, **kwargs):
    try:
        app = await model.deploy("ubuntu")
        await model.block_until(lambda: all(u[0].workload_status == 'active' for u in app.units))
        await app.refresh(**kwargs)
    finally:
        await app.remove()
        await model.block_until(lambda: not len(model.applications))

if __name__ == '__main__':
    jasyncio.run(main())
```

### CODE REVIEW

**Review by cderici — APPROVED** [review]
LGTM 👍

**Comment by jack-w-shaw** [comment]
NOTE: The uni integration test failure is a timeout, which passes when I try locally. Merging anyway

**Pull request merged**
