### PR TITLE
Implement scp functionality

### PR DESCRIPTION
**Pull request by Cynerva**
This adds scp methods to the Unit and Machine classes. I had to redefine the interfaces a little bit since the previous scp stubs didn't account for push vs. pull.

Also added a couple properties along the way, `unit.machine` and `machine.public_address`.

### CODE REVIEW

**Comment by johnsca** [comment]
The failure from Travis is:

```
tests/integration/test_machine.py::test_scp Warning: Identity file ~/.local/share/juju/ssh/juju_id_rsa not accessible: No such file or directory.
ssh: Could not resolve hostname none: Name or service not known
```

Further down is the command executed:

```
E           juju.errors.JujuError: command failed: ['scp', '-i', '~/.local/share/juju/ssh/juju_id_rsa', '-o', 'StrictHostKeyChecking=no', '/tmp/tmpf5khpgto', 'ubuntu@None:testfile']
juju/machine.py:178: JujuError
```

There also seem to be some subsequent SSL-related failures on the websocket, but I suspect those are spurious.

**Comment by johnsca** [comment]
I'm not clear on what the need is for separate `scp_to` vs `scp_from` commands?  The Juju CLI is able to handle both with a single command, as is the underlying `scp` command, so I'd much prefer to preserve that.  It just means being able to detect unit names in either param.  It might also be worth supporting multiple source files, like the `scp` client does.

**Comment by johnsca** [comment]
Regarding the failures in Travis, it looks like you need to use `os.path.expanduser()` (or `pathlib.Path().expanduser()`) and the host ended up being `None` so there's an issue with the logic for that.

**Comment by Cynerva** [comment]
> I'm not clear on what the need is for separate scp_to vs scp_from commands?

The interface we had before didn't make sense to me:
```
unit = model.units['ubuntu/0']
unit.scp('localpath', 'ubuntu/0:remotepath')
```

Having a `Unit.scp` method where you have to specify the name of the unit seems silly. Here are the alternatives I came up with:

1. Split it up into `scp_to` and `scp_from`:
```
unit.scp_to('localpath', 'remotepath')
unit.scp_from('remotepath', 'localpath')
```
2. Use a simpler prefix like `remote`:
```
unit.scp('localpath', 'remote:remotepath')
```
3. Move the `scp` method to `Model`:
```
model.scp('localpath', 'ubuntu/0:remotepath')
```

I'm not a fan of APIs that require string manipulation -- seems error prone, and harder to read when you have to build strings dynamically -- so I went for option 1. I'm open to changing it however.

**Comment by Cynerva** [comment]
Added the `os.path.expanduser` bit, thanks!

Regarding the hostname=None bit, I'm able to repro locally. The problem is that LXD machines are never assigned a public address. Here's what I see in `machine.data['addresses']` instead:
```
[{'scope': 'local-cloud', 'type': 'ipv4', 'value': '10.44.92.183'},
 {'scope': 'local-machine', 'type': 'ipv4', 'value': '127.0.0.1'},
 {'scope': 'local-machine', 'type': 'ipv6', 'value': '::1'}]
```

I'mma go stare at the Juju CLI golang for a while and see how they handle it.

**Comment by Cynerva** [comment]
Rebased to resolve conflicts. Added a couple commits to get this working on LXD. This solution doesn't seem quite proper, but I can't come up with anything better.

**Comment by Cynerva** [comment]
@johnsca The tests failed, but it doesn't look related to anything from this PR as far as I can tell. Any idea what's up?

**Pull request merged**
