### PR TITLE
Babysitting python3.5

### PR DESCRIPTION
**Pull request by cderici**
### Description

This PR attempts to fix all the CI test issues for python3.5

Update: We now seem to be consistently getting green for `python3.5` :+1: 

### QA Steps

Unit & integration tests for python3.5 should pass

### Notes & Discussion

There's apparently still some intermittent errors for other Python versions, which will be addressed later. This PR is only about `python3.5`.

### CODE REVIEW

**Comment by cderici** [comment]
!!build!!

**Comment by cderici** [comment]
!!build!!

**Comment by cderici** [comment]
!!build!!

**Review by SimonRichardson — APPROVED** [review]

**Comment by cderici** [comment]
$$merge$$

**Pull request merged**
