### PR TITLE
Update facades for juju 2.9.1

### PR DESCRIPTION
**Pull request by tlm**
Updates facades to Juju 2.9.1

### CODE REVIEW

**Review by wallyworld — APPROVED** [review]

**Comment by tlm** [comment]
$$merge$$

**Comment by tlm** [comment]
$$merge$$

**Comment by tlm** [comment]
$$merge$$

**Comment by tlm** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

Intermittent test failure

> [gw1] FAILED tests/unit/test_relation.py::TestRelation::test_relation_does_match

**Comment by SimonRichardson** [comment]
!!build!!

Failed for a different reason

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
$$merge$$

**Pull request merged**
