### PR TITLE
Add an offer to the existing bundle test

### PR DESCRIPTION
**Pull request by sed-i**
#### Description

- [x] Demonstrate #816: reproduced [in CI](https://github.com/juju/python-libjuju/actions/runs/4431006367/jobs/7773478291#step:6:405).
- [x] Commit fix

#### QA Steps

```
tox -e integration -- tests/integration/bundle
```

### CODE REVIEW

**Comment by sed-i** [comment]
@juanmanuel-tirado the original error is gone but there's [a new one](https://github.com/juju/python-libjuju/actions/runs/4433509759/jobs/7778631597#step:6:411) now:
```
   File "/home/runner/work/python-libjuju/python-libjuju/juju/offerendpoints.py", line 35, in parse_offer_endpoint
    raise ParseError("endpoint must conform to format \"<application-name>:<endpoint-name>\"")
juju.offerendpoints.ParseError
```
Not sure I'd be able to look into this in the next few days. Feel free to take over if you like.

**Comment by sed-i** [comment]
@juanmanuel-tirado would you have a moment to take a look at the itest failure? Not sure why this fails.

**Comment by sed-i** [comment]
Hey @cderici,
There's a very obvious bug this PR was trying to fix, but I haven't looked into why CI fails.
Would you be able to take a look?

**Comment by cderici** [comment]
> Hey @cderici, There's a very obvious bug this PR was trying to fix, but I haven't looked into why CI fails. Would you be able to take a look?

Absolutely, I'll take a look today, thanks for the reminder, sorry I missed this before.

**Comment by sed-i** [comment]
If CI now passes we may want to restore [the test that I dropped](https://github.com/juju/python-libjuju/pull/817/commits/735236811d442389600ad61a0fb609c51acfb5f1).

**Comment by cderici** [comment]
The CI is failing for unrelated reasons, so I think we can safely land this.

But before that I'd like to see if that test actually reproduces this, in which case we should definitely keep 735236811d442389600ad61a0fb609c51acfb5f1. Unfortunately the logs for the run when you pushed it have expired so I can't see their outputs, but I may go ahead and try it myself manually.

But other than that, I'll give this a thumbsup, it's an obvious fix as you said.

**Comment by sed-i** [comment]
Hi @cderici 
I restored the test. CI shouldn't fail as per issue because the fix is in place, but now it would be easier to confirm locally.

**Comment by cderici** [comment]
@sed-i so the join is part of the problem here, looks like the main offense comes from that we just don't support endpoint syntax  without `:` in pylibjuju https://github.com/juju/python-libjuju/blob/ad62156b3bd18c949cd7f65a6b528cbaf023e121/juju/offerendpoints.py#L34

Fix is coming soon 👍

**Comment by cderici** [comment]
#887 takes over, so closing this. (@sed-i your commits are not discarded, I just moved them to the new PR, feel free to push there as well 👍 )

**Pull request closed without merging**
