### PR TITLE
Fix bug #519 and #522: Add local resources for bundles

### PR DESCRIPTION
**Pull request by davigar15**

### CODE REVIEW

**Review by SimonRichardson — COMMENTED** [review]
Yes, looks in line with what juju does. Just add a test and I'll happily land this.

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Review by SimonRichardson — APPROVED** [review]

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by hpidcock** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
$$merge$$

**Pull request merged**
