### PR TITLE
Add REPL quickstart subsection

### PR DESCRIPTION
**Pull request by sed-i**
This PR adds a short section to the readme describing how to use the library directly in a REPL.

### CODE REVIEW

**Review by juanmanuel-tirado — APPROVED** [review]
LG2M
Thanks for the contribution.

**Comment by cderici** [comment]
@sed-i I believe the CI here is stuck with one of the weird CI issues we were having lately and requires one of the recent fixes for it, simple rebase on the main branch should make it mergable :+1:

**Comment by sed-i** [comment]
Rebased. Thanks @cderici!

**Pull request merged**
