### PR TITLE
[JUJU-3552] Prepare 3.1.2.1 release

### PR DESCRIPTION
**Pull request by juanmanuel-tirado**
#### Description

* Add juju schema facades for 3.1.2. 
* The compatibility message between versions has been moved to `debug` instead of warning.
* Secret facades testing has been revisited.

#### QA Steps

All CI tests need to pass.

The tests using the ubuntu charm fail due to the inclusion of storage in the latest charm.

#### Notes & Discussion

Before releasing 3.1.2.1 we need to land #833 and #830

### CODE REVIEW

**Comment by juanmanuel-tirado** [comment]
Surprisingly there are no unit tests failing. In local everything runs smoothly, but it fails in Github...

**Review by cderici — APPROVED** [review]
LGTM. Successfully tried a couple of integration tests on fresh controller.

**Comment by juanmanuel-tirado** [comment]
Tests are hitting timeouts in GitHub runners. Tests pass in local environments.

**Pull request merged**
