### PR TITLE
Add regression test for ApplicationStatus units empty

### PR DESCRIPTION
**Pull request by tbaumann**
This only adds the regression test, not the fix!

#### Description
Tests bug https://github.com/juju/python-libjuju/issues/780

The units list is empty for all subordinates

#### QA Steps

```
python -m pytest --tb native -rP -v -k 'subordinate_units'
```
or
```
tox -e integration -- tests/integration/test_model.py -k 'subordinate_units' -m 'not serial'
..
```

#### Notes & Discussion

See https://github.com/juju/python-libjuju/issues/780

### CODE REVIEW

**Review by juanmanuel-tirado — CHANGES_REQUESTED** [review]
I think it looks OK, I've just updated the branch with the latest changes from master. Just one minor request. Could we use jammy series instead of bionic?

Thanks for the PR

**Comment by tbaumann** [comment]
> I think it looks OK, I've just updated the branch with the latest changes from master. Just one minor request. Could we use jammy series instead of bionic?

Sure, I will change that. 

Do you have an idea on the fix yet? Because if you merge this it will fail the integration until it's fixed. I hope that intention was clear.

**Comment by cderici** [comment]
As I mentioned in https://github.com/juju/python-libjuju/issues/780#issuecomment-1570988234, this looks like expected behavior.

**Comment by tbaumann** [comment]
> I think it looks OK, I've just updated the branch with the latest changes from master. Just one minor request. Could we use jammy series instead of bionic?

Of course

**Pull request closed without merging**
