### PR TITLE
Switch from Travis to GitHub Actions

### LINKED ISSUE #400: travis ci broken?
every single commit in this repo for many moons and every single pr on this repo are failing status checks, which conveys a connotation of a project thats not really working. if your not using travis then remove the .travis.yml config from this repo or fix.

### LINKED ISSUE #421: Return value for model.get_action_output() has changed
`test_run_action` is failing with:

```
Traceback (most recent call last):
  File "/home/johnsca/juju/libs/python-libjuju/tests/integration/test_unit.py", line 60, in test_run_action
    assert action.results == {'dir': '/var/git/myrepo.git'}
AssertionError: assert {'Code': '0',...t/myrepo.git'} == {'dir': '/var/git/myrepo.git'}
  Omitting 1 identical items, use -vv to show
  Left contains 2 more items:
  {'Code': '0',
   'Stdout': "Adding group `myrepo' (GID 1001) ...\n"
             'Done.\n'
             'Initialized empty Git repository in /var/git/myrepo.git/\n'}
```

### PR DESCRIPTION
**Pull request by johnsca**
Tests were consistently failing on Travis and not giving any useful debugging info.  Switching to GitHub Actions (and removing the PPAs) gets to the actual real test failures so that they can be debugged.

Closes #400
Fixes #421

### CODE REVIEW

**Comment by petevg** [comment]
$$merge$$

**Comment by petevg** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by johnsca** [comment]
I cherry-picked #418 into this hoping to get a full passing run.  Uncovered at least #420 and #421

**Comment by johnsca** [comment]
!!build!!

**Comment by johnsca** [comment]
$$merge$$

**Comment by hpidcock** [comment]
@johnsca thank-you for working on this

**Pull request merged**
