### PR TITLE
Fix formatting of addresses passed to SCP

### LINKED ISSUE #424: scp_from/scp_to renders invalid address format when IPv6 is used
IPv6 addresses need to be encapsulated in '[]'

https://github.com/juju/python-libjuju/blob/91194f08a34c33bce9eb2579587b305969ef8432/juju/machine.py#L157

### PR DESCRIPTION
**Pull request by fnordahl**
When using SCP to a machine with an IPv6 address the IPv6 address
must be encapsulated in brackets ('[]').

Fixes #424

### CODE REVIEW

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
Finally! @fnordahl sorry it took so long.

**Comment by fnordahl** [comment]
No worries, thank you for your persistence in getting it merged @SimonRichardson

**Pull request merged**
