### PR TITLE
[JUJU-3894] Forward port some fixes from 2.9 to master

### PR DESCRIPTION
**Pull request by cderici**
#### Description

This cherry-picks the following from `2.9` onto the `master`:

- 6f80985f6c1bef1c63dd12e29f9e4f70473c92d1, fc2f39ce55708255857887b7eaa8700d2949d204  from #868
- da8de1d432e8324c39217574296502a34d663ae0, 4b4f60c562ff0527192a26659672acabeb4b5783 from #854 
- 6642cfe6453bff12c6f3d90422da2f8b22f64ae2, 6e9950e955ee1bb5acfadc68a6a460a1c0fd02c9, a74208bc5d99489f974461ba1e35242545b28685 from #846 
- e4b8a809425eeca36a372cc28016273e13bd38aa, 828641832afcb79b62c41a5675952e11c8ac16d6, 4efa2662f9a6af51f5a51aecf28b4dc52f7a9671 from #849
- fa0ae505450db6597c86d660f1de451f34c2626f from #833

The `wait_for_idle` stuff:

- 521a7ac bcf3e13 from #840 
- 91a84e4 1d56446 from #833

#### QA Steps

All the QA steps in the following need to be performed to make sure things are working well.

- #854 [DONE - cderici]
- #868 [DONE - cderici]
- #846 [DONE - cderici]
- #849 [DONE - cderici]
- #833 [DONE - cderici]

All CI tests need to pass.

### CODE REVIEW

**Comment by juanmanuel-tirado** [comment]
Have we tested #854?

```python
from juju import model;m = model.Model(); await m.connect(); await m.deploy("postgresql", channel="14/edge")
....
File ~/code/python-libjuju/juju/client/facade.py:689, in Type.from_json(cls, data)
    686             d[key] = value
    687         else:
    688             # this is a simple entry
--> 689             cls.splitEntries(entry, d)
    690     return cls(**d)
    691 return None

AttributeError: type object 'ExpressionTree' has no attribute 'splitEntries'

```
And #868?
```python
from juju import model; m=model.Model(); await m.connect();await m.deploy('./tests/integration/charm-series-kubernetes')
...
File ~/code/python-libjuju/juju/client/connection.py:660, in Connection.rpc(self, msg, encoder)
    658             err_results.append(res['error']['message'])
    659     if err_results:
--> 660         raise errors.JujuError(err_results)
    662 elif result['response'].get('error', {}).get('message'):
    663     raise errors.JujuError(result['response']['error']['message'])

JujuError: ['cannot add application "charm": series "" not supported by charm, supported series are "kubernetes"']
```

**Comment by juanmanuel-tirado** [comment]
#854 use case works now

**Comment by cderici** [comment]
#868 should work now, bringing [this ](https://github.com/juju/juju/blob/781f3b966a63d6188c86479ecb933311ec4aa51a/cmd/juju/application/utils/origin.go#L37)from the juju cli fixed it 👍

**Comment by cderici** [comment]
I just manually ran all the failing tests locally and they all seem to be passing. In particular, the ones I ran were : 

- `tests/integration/test_model.py::test_unit_annotations`
- `tests/integration/test_model.py::test_add_and_list_storage`
- `tests/integration/test_model.py::test_deploy_local_charm`
- `tests/integration/test_model.py::test_local_file_resource_charm`

they were failing with either connection closed, or cancelled.

I believe there's an internal gotcha about Github actions that we're not aware of yet. One thing we can do about this is to bring back 1 jenkins job for integration tests, so we could at least normalize the CI run across different platforms.

**Comment by juanmanuel-tirado** [comment]
I have manually tested all the failing tests, and they pass in a local environment. I will approve and merge this PR.

**Review by juanmanuel-tirado — APPROVED** [review]

**Pull request merged**
