### PR TITLE
Update websockets library to work with Py3.10

### PR DESCRIPTION
**Pull request by fnordahl**
The current pin for websockets does not work for Python 3.10 due
to the change of the asyncio event loop API.

### CODE REVIEW

**Comment by hpidcock** [comment]
!!build!!

**Comment by hpidcock** [comment]
!!build!!

**Comment by cderici** [comment]
!!build!!

**Comment by juanmanuel-tirado** [comment]
!!build!!

**Comment by juanmanuel-tirado** [comment]
!!build!!

**Review by cderici — APPROVED** [review]
I ran the CI tests locally, we can go ahead and land this. Thanks for the PR @fnordahl!

**Comment by cderici** [comment]
$$merge$$

**Comment by cderici** [comment]
$$merge$$

**Comment by addyess** [comment]
did this get merged?
i raised this https://github.com/juju/python-libjuju/pull/673

**Comment by cderici** [comment]
#673 is landed, covers this one as well :+1:

**Pull request closed without merging**
