### PR TITLE
Handle OSError Network Unreachable

### PR DESCRIPTION
**Pull request by thedac**
Try each endpoint for the controller until success, only throw an
exception if all endpoints have been attempted and failed.

Without this change, the client will throw an OSError exception when for
example trying to access the fan network from a host that is not on that
fan network.

Closes Issue: https://github.com/juju/python-libjuju/issues/426

### CODE REVIEW

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by petevg** [comment]
!!build!!

**Comment by petevg** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
$$merge$$

**Pull request merged**
