### PR TITLE
[JUJU-3927] Add 3.2.0 facades 

### PR DESCRIPTION
**Pull request by juanmanuel-tirado**
#### Description

This PR adds the latest facades from Juju 3.2.0, and prepares GitHub actions to use 3.2/stable

#### QA Steps

GitHub actions should be green. In any case, local testing should work:

```
tox -e integration -- tests/integration/...
```

### CODE REVIEW

**Comment by juanmanuel-tirado** [comment]
Running locally I got:
```
FAILED tests/integration/test_controller.py::test_list_models_user_access - AssertionError: assert 3 > 3
FAILED tests/integration/test_controller.py::test_destroy_model_by_name - asyncio.exceptions.CancelledError
FAILED tests/integration/test_model.py::test_deploy_local_bundle_dir - asyncio.exceptions.CancelledError
FAILED tests/integration/test_model.py::test_deploy_local_bundle_include_file - asyncio.exceptions.CancelledError
FAILED tests/integration/test_model.py::test_add_and_list_storage - asyncio.exceptions.CancelledError
```

`tests/integration/test_controller.py::test_list_models_user_access` is particularly concerning and could be a regression in juju 3.2.0

**Comment by cderici** [comment]
> Running locally I got:
> 
> ```
> FAILED tests/integration/test_controller.py::test_list_models_user_access - AssertionError: assert 3 > 3
> FAILED tests/integration/test_controller.py::test_destroy_model_by_name - asyncio.exceptions.CancelledError
> FAILED tests/integration/test_model.py::test_deploy_local_bundle_dir - asyncio.exceptions.CancelledError
> FAILED tests/integration/test_model.py::test_deploy_local_bundle_include_file - asyncio.exceptions.CancelledError
> FAILED tests/integration/test_model.py::test_add_and_list_storage - asyncio.exceptions.CancelledError
> ```
> 
> `tests/integration/test_controller.py::test_list_models_user_access` is particularly concerning and could be a regression in juju 3.2.0

Yeah I'm trying to run these as well, for some reason my python environment just blew up trying to recover 🤦

**Review by cderici — APPROVED** [review]
Yeah the regression confirmed for the `tests/integration/test_controller.py::test_list_models_user_access`. It passes against the `3.1` and fails in `3.2`. Looking closely, this seems to be a regression in the `ModelManagerFacade.ListModels()` in Juju. Created a [ticket ](https://warthogs.atlassian.net/browse/JUJU-3952?atlOrigin=eyJpIjoiZWY5MzQ0YjIzZjQyNGM1NzgxZWU5ZWIwZmExYTYxMTMiLCJwIjoiaiJ9) for that.

I approve this PR because 1) the regression is not about libjuju itself, and 2) everything else seems to be working fine. I manually ran all the failing tests and they seem to be working individually, so we're good to go for 3.2 👍

**Comment by juanmanuel-tirado** [comment]
As you already mentioned, I will ignore the regression on the Juju side and move this PR forward. Thanks for double checking!

**Pull request merged**
