### PR TITLE
setup.py: adjust websockets versions for py38-310

### PR DESCRIPTION
**Pull request by mert-kirpici**
According to the [websockets changelog](https://websockets.readthedocs.io/en/stable/project/changelog.html):
  - v8.0 requires python >= 3.6
  - v8.1 adds support for python3.8
  - v9.0 adds support for python3.9
  - v10.0 adds support for python3.10

This change is attempting to cover all these scenarios. The previous behavior was allowing some unwanted scenarios, e.g. websockets==9.0 and python3.10 combination. Which is incompatible.

Fixes: #730

### CODE REVIEW

**Comment by cderici** [comment]
@mert-kirpici thanks for the change! Let's see the integration tests with the different py versions for now, I'll take a closer look as soon as I can :+1: çok selamlar!

**Comment by mert-kirpici** [comment]
hey @cderici, I'll appreciate the review! teşekkürler :slightly_smiling_face:

**Review by juanmanuel-tirado — APPROVED** [review]
LG2M

Thanks!

**Pull request merged**
