### PR TITLE
ci: use fail-fast, not continue-on-error

### PR DESCRIPTION
**Pull request by dimaqq**
Looks like I was wrong in #1163 
Using https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast instead.
Skip tests that are guaranteed to fail against older Juju controllers.

### CODE REVIEW

**Review by SimonRichardson — COMMENTED** [review]
The postgres charm should have an assumes block in the metadata yaml, which should state that it doesn't work for less than 3.3.0.

**Comment by dimaqq** [comment]
It probably does.
I don't have the error snippet ready, but the error suggested that several charm revisions were considered, but there was no charm revision that could be run.
I've opened https://github.com/juju/python-libjuju/pull/1173 with a single skip disabled to catch the actual detailed error.

The point of this PR is that it doesn't make sense to run a test that uses secrets facade v2 or deploys postgresql against older Juju versions, these tests will always fail.

**Comment by dimaqq** [comment]
Here's the error that is encountered against Juju 3.1:

```
Charm feature requirements cannot be met:
  - charm requires at least one of the following:
    - charm requires all of the following:
      - charm requires feature "juju" (version < 3.0.0) but model currently supports version 3.1.10
    - charm requires all of the following:
      - charm requires feature "juju" (version >= 3.4.3) but model currently supports version 3.1.10
    - charm requires all of the following:
      - charm requires feature "juju" (version >= 3.5.1) but model currently supports version 3.1.10

Feature descriptions:
  - "juju": the version of Juju used by the model

For additional information please see: https://juju.is/docs/olm/supported-features
```

**Comment by dimaqq** [comment]
Limiting this PR to only fixing the CI, without any code changes.

**Review by james-garner-canonical — APPROVED** [review]

**Pull request merged**
