### PR TITLE
Release 2.9.3 notes

### PR DESCRIPTION
**Pull request by SimonRichardson**
2.9.3
^^^^^

Monday August 12 2021

* Bug fix - Fix 'Default to bundle series if the charm has no series
field' #514

### CODE REVIEW

**Review by jameinel — APPROVED** [review]
Assuming you intended to just do a version and changelog change, LGTM

If this was intended to include the actual bug fix, then seems like it needs work :)

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Pull request merged**
