### PR TITLE
fix(labels): change stalebot exempt labels

### PR DESCRIPTION
**Pull request by Aflynn50**
#### Description

Changes the exempt labels for the stalebot:

    use stalebot/disabled and kind/wishlist for issues
    use stalebot/disabled and state/awaiting-approval for PRs

### CODE REVIEW

**Review by jack-w-shaw — APPROVED** [review]

**Review by dimaqq — APPROVED** [review]

**Comment by dimaqq** [comment]
@Aflynn50 pls rebase

**Comment by james-garner-canonical** [comment]
Should `state/in-progress` also disable stalebot the way `work-in-progress` did previously? I guess in a way it's better to add the `stalebot/disable` label explicitly.

**Pull request merged**
