### PR TITLE
Adding comment in example/controller.py regarding cloudcred format

### PR DESCRIPTION
**Pull request by sfeole**
Possible Typo in the Example/Controller.py
I updated cloud-creds:  :s/@/_

'cloudcred-aws_tvansteenburgh_external_aws-tim',

For LXD I used:
'cloudcred-localhost_admin_default'

'cloudcred-localhost_admin@default' fails, unless the @ is intentional for AWS

### CODE REVIEW

**Comment by tvansteenburgh** [comment]
Yeah this is a great observation, but it's not actually a typo. In my scenario it was required (shared controller on aws). At least I think it was required - didn't try it w/o the '@external'. But at the very least, it worked. Maybe change the PR to add a comment in the example about the cloudcred format instead, to assist future users?

**Comment by sfeole** [comment]
Hey Tim, I looked at this again, You are infact following the cloudcred format as in: 
cloudcred-<cloudname>_<user>_<credentialname>
The '@' completely threw me off :) 

I updated the example comments to add a 2 line note there, if that works?

**Comment by sfeole** [comment]
I think this is something that documentation would fix, when that becomes available.

**Comment by tvansteenburgh** [comment]
@sfeole Thanks!

**Pull request merged**
