### PR TITLE
[JUJU-1353] Parse assume directives.

### LINKED ISSUE #684: Error deploying sidecar and podspec charms using ops_test
When deploying both sidecar and podspec charms in a test using `ops_test.model.deploy`, we get an error:
```
Traceback (most recent call last):
  File "/home/ubuntu/code/dex-auth/tests/integration/test_charm.py", line 73, in test_relations
    await ops_test.model.deploy(istio_pilot, channel="latest/edge", trust=True)
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/model.py", line 1644, in deploy
    resources = await self._add_charmhub_resources(res.app_name,
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/model.py", line 1762, in _add_charmhub_resources
    res = await charm_facade.CharmInfo(entity_url)
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 501, in wrapper
    result = cls.from_json(reply['response'])
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 672, in from_json
    return cls(**d)
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/client/_definitions.py", line 4800, in __init__
    meta_ = CharmMeta.from_json(meta) if meta else None
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 672, in from_json
    return cls(**d)
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/client/_definitions.py", line 5312, in __init__
    assumes_expr_ = ExpressionTree.from_json(assumes_expr) if assumes_expr else None
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 668, in from_json
    for k, v in (data or {}).items():
AttributeError: 'list' object has no attribute 'items'
```
The podspec charm uses `min-juju-version` and `series: [kubernetes]` while sidecar uses `assumes: juju >= 2.9.0`. We suspect that they are somehow interfering each other and causing that error. The charms can be deployed in the same model using CLI.

This issue was consulted with @cderici and it looks like it's about how the `assumes` field in the charm's metadata is communicated through the API.

### PR DESCRIPTION
**Pull request by juanmanuel-tirado**
By using [assumes](https://juju.is/docs/sdk/assumes) the current parser in the `facades.py` breaks. This PR adds a basic initial solution to support assumes and unblock some of the existing issues.

Note that the `any-all` assume is not supported in this PR.

This is intended to fix #684

### CODE REVIEW

**Comment by jnsgruk** [comment]
We probably want some tests for this?

**Comment by juanmanuel-tirado** [comment]
Sure. I was waiting for some confirmation from the affected ones :)

**Comment by natalian98** [comment]
Hi @juanmanuel-tirado this seems to fix my issue, now both sidecar and podspec charms can be deployed in the same test.
Thanks a lot!

**Comment by juanmanuel-tirado** [comment]
Thanks for checking. I will prepare some testing and commit.

**Pull request merged**
