### PR TITLE
Upload credential to controller when adding model

### PR DESCRIPTION
**Pull request by johnsca**

### CODE REVIEW

**Comment by johnsca** [comment]
[(2) Add UpdateCredentials to add_model](https://trello.com/c/n1HfwyJX/90-2-add-updatecredentials-to-addmodel)

**Comment by tvansteenburgh** [comment]
How was this tested?

**Comment by johnsca** [comment]
I couldn't think of a way to create an automated test for this, since the LXD provider doesn't really use credentials.  I ran the following manual test:

```python
import logging
from juju import loop
from juju.controller import Controller

logging.basicConfig()
log = logging.getLogger('test')
log.setLevel(logging.INFO)
juju_log = logging.getLogger('juju')
juju_log.setLevel(logging.DEBUG)

async def main():
    controller = Controller()
    model = None
    log.info('Connecting to controller')
    await controller.connect_controller('jaas')
    try:
        log.info('Adding model')
        model = await controller.add_model(
            'test',
            cloud_name='aws',
            credential_name='canonical-juju-copy2')
        log.info('Deploying cs:~johsca/libjuju-test')
        app = await model.deploy('cs:~johnsca/libjuju-test')
        log.info('Waiting for units')
        await model.block_until(lambda: app.units)
    finally:
        log.info('Cleaning up')
        if model:
            log.info('Removing model')
            model_uuid = model.info.uuid
            await model.disconnect()
            await controller.destroy_model(model_uuid)
        log.info('Disconnecting')
        await controller.disconnect()


loop.run(main())
```

And these were the results (note the cloud credential tag in the ModelInfo):

```
INFO:test:Connecting to controller
INFO:test:Adding model
DEBUG:juju.controller:Uploading credential canonical-juju-copy2
DEBUG:juju.controller:Creating model test
DEBUG:juju.model:Starting watcher task
DEBUG:juju.model:Got ModelInfo: {'sla': None, 'default_series': 'xenial', 'name': 'test', 'migration': None, 'status': <juju.client._definitions.EntityStatus object at 0x7fbc17491278>, 'cloud_region': 'us-east-1', 'provider_type': 'ec2', 'controller_uuid': '', 'users': [], 'cloud_credential_tag': 'cloudcred-aws_johnsca@external_canonical-juju-copy2', 'agent_version': <Number major=2 minor=2 patch=2 tag= build=0>, 'uuid': '4e5fc1e7-012d-4ca4-8615-8499a963f080', 'owner_tag': 'user-johnsca@external', 'life': 'alive', 'cloud_tag': 'cloud-aws', 'machines': []}
INFO:test:Deploying cs:~johsca/libjuju-test
INFO:juju.model:Deploying cs:~johnsca/libjuju-test-1
DEBUG:juju.model:Model changed: unit add libjuju-test/0
DEBUG:juju.model:Model changed: application add libjuju-test
INFO:test:Waiting for units
INFO:test:Cleaning up
INFO:test:Removing model
DEBUG:juju.model:Stopping watcher task
DEBUG:juju.model:Closing model connection
DEBUG:juju.controller:Destroying model 4e5fc1e7-012d-4ca4-8615-8499a963f080
INFO:test:Disconnecting
DEBUG:juju.controller:Closing controller connection
```

**Comment by tvansteenburgh** [comment]
I think it'd be worth adding your test to the repo, maybe as a `credential.py` in `examples/` ?

**Pull request merged**
