### PR TITLE
feat(client-only-schemas): remove schemas for EOL Juju 3.2

### PR DESCRIPTION
**Pull request by james-garner-canonical**
Remove `3.2.X` schemas. Delete `_client*.py` and run `make client`.

#### Description

Moving towards the goal of having schemas and generated code in python-libjuju only for the latest supported Juju versions (`3.1.9`, `3.3.6`, `3.5.4`, `3.5.3`), and using client only schemas (see #1099), this PR removes schemas for EOL Juju 3.2, and reruns code generations, removing `_client*.py` files and then running `make client`.

#### QA Steps

CI steps should all continue to pass, except for integration testing which should continue to fail with the usual suspects (see #1108 for a non-exhaustive table of tests that sometimes fail on `main`). 

#### Notes

To hopefully simplify the diffs, this is the first PR in a planned sequence of PRs that will depend on each other. Subsequent PRs will be:
1. replace current schemas with latest release client only schemas (`3.1.9`, `3.3.6`) and regenerate code
2. add client only schema for `3.4.5` and regenerate code
3. add client only schema for `3.5.3` and regenerate code

### CODE REVIEW

**Review by dimaqq — CHANGES_REQUESTED** [review]
given that _client18 get removed, I'm pretty sure these lines need to be updated:

```py
juju/client/_client.py
26:from juju.client import _client7, _client1, _client3, _client4, _client2, _client17, _client6, _client11, _client10, _client5, _client9, _client18, _client19
41:    "18": _client18,
```

**Comment by dimaqq** [comment]
Funnily enough, `_client12` was never imported in the first place 🚀

**Comment by james-garner-canonical** [comment]
> given that _client18 get removed, I'm pretty sure these lines need to be updated:

Actually, _client18 is the only one that wasn't removed, and was instead modified. So the imports are correct, which is a relief since they're from codegen.

Easy to miss that _client18 is still there in the Files changed tab as the diff is also hidden due to being too large.

**Comment by dimaqq** [comment]
Ah, so true!

**Review by dimaqq — APPROVED** [review]

**Pull request merged**
