### PR TITLE
fix: machine scp/ssh operations

### PR DESCRIPTION
**Pull request by yanksyoon**
#### Description

*\<Please add why this change is needed and what it does.\>*
This is a follow up PR to [#1015](https://github.com/juju/python-libjuju/pull/1015)
This addresses the issue #997 

The current machine.ssh or machine.scp will fail due to machine address not being ready.
This makes the machine ssh command become `ssh ubuntu@None`.

*\<Fixes: \>*
Added a function `machine.wait()` which waits for machine agent to become ready and the machine address to exist.
The scp/ssh functions now will raise if `await machine.wait()` hasn't been called.

#### QA Steps

```
tox -e integration -- -k test_machine_ssh
```

All CI tests need to pass.

*\<Please note that most likely an additional test will be required by the reviewers for any change that's not a one liner to land.\>*

#### Notes & Discussion

*\<Additional notes for the reviewers if needed. Please delete section if not applicable.\>*

### CODE REVIEW

**Comment by tlm** [comment]
@cderici mind taking a look? Or happy to do a dual review if you want to shadow me through this to make sure my assumptions are correct?

**Review by cderici — COMMENTED** [review]
This is nice, but instead of failing in `machine.ssh` and `machine.scp`, I'd add an optional `wait_until_active=False` argument and inline the body of `wait()` in where you're currently raising an error. Note that `block_until` is defined in the model, so you're gonna need to call it like `self.model.block_until()` in `Machine` methods.

Also this in it's current implementation requires heavy testing, as the `status` is a bit finicky in pylibjuju, as the status we get through the api is not exactly the same status you'd see via juju-cli (i.e. `juju status`). For machines it shouldn't be too much of a problem, however, I would refrain from checking the status directly (like `self.agent_status == "started"`), as there might be a race where in between the block_until check intervals the status might change and you'd lose the time to catch it, so I wouldn't want my code to rely on the status itself. Instead I'd check just the addresses, as that's what you essentially need.

However, `safe_data` shouldn't be used outside the class, as it's internal, so let's add a `machine.addresses()` method and use that (also in the `machine.dns_name()` as well). WDYT?

**Comment by yanksyoon** [comment]
Thank you for the review @cderici !

I've applied the changes - but since this was branched off of #1015 , shall I wait until the conversation there is resolved? Or I could cherry-pick the changes for this PR and branch if off of main again :)

**Comment by yanksyoon** [comment]
@cderici I've created #1020 with cherry-picked commits, I'll close this one! Thank you for the feedback so far! :D

**Pull request closed without merging**
