### PR TITLE
Charmstore compatability of deploying bundles

### PR DESCRIPTION
**Pull request by addyess**
Addressing issue https://github.com/juju/python-libjuju/issues/649

### CODE REVIEW

**Review by SimonRichardson — APPROVED** [review]
Nice, thanks for the change.

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by addyess** [comment]
I see failures, but i can't tell if they're failures i've caused.

**Comment by juanmanuel-tirado** [comment]
!!build!!

**Comment by cderici** [comment]
@addyess The test failures are not about your work, this PR can be merged.

I see the failing test, namely `test_list_models_user_access` failing in my PR as well. Note that it's passing for your PR on the edge.

**Comment by addyess** [comment]
Thanks @cderici and @SimonRichardson. I don't have merge privs on this repo.  Would either of you mind merge + releasing.  Thanks so much

**Pull request merged**
