### PR TITLE
[JUJU-1542] Fix run actions on units

### PR DESCRIPTION
**Pull request by cderici**
#### Description

This changes the function that's used for running an action on a unit from `Action.Enqueue` to `Action.EnqueueOperation`, because it's the most up to date one and also the former one is deprecated in `Action v7` facade.

- [ ] Should be merged after #697 has landed.

#### QA Steps

The qa steps I followed were with a k8s model. So get a controller on a k8s cloud. 
The following then should work fine.

```python
async def _get_password():
    model = Model()
    await model.connect()
    await model.deploy('zinc-k8s')
    await model.wait_for_idle(status="active")

    unit = model.applications['zinc-k8s'].units[0]
    action = await unit.run_action("get-admin-password")
    results = await action.wait()
    print(results["admin-password"])
    await model.disconnect()
```

#### Notes & Discussion

* Maybe we should also add an integration test with an example action to make sure we won't regress from this in the future.

### CODE REVIEW

**Comment by juanmanuel-tirado** [comment]
Rerun tests after merging #697

**Review by juanmanuel-tirado — APPROVED** [review]
LG2M

**Comment by sed-i** [comment]
I'm now [getting](https://github.com/canonical/prometheus-k8s-operator/runs/7638474213?check_suite_focus=true#step:5:1440)
```
  File "/home/runner/work/prometheus-k8s-operator/prometheus-k8s-operator/.tox/integration/lib/python3.8/site-packages/juju/unit.py", line 167, in run_action
    res = await action_facade.EnqueueOperation(actions=[client.Action(
AttributeError: 'ActionFacade' object has no attribute 'EnqueueOperation'
```
Not sure if it's because of this change.

**Comment by cderici** [comment]
It's for sure because of this change, but afaik the juju `2.9`'s `Action v6` facade should have an `EnqueueOperation` function. Is it possible for you to upgrade to `juju 2.9/stable` (that's `2.9.32` I think)?

**Comment by sed-i** [comment]
Oh nice, I didn't know.
Most (all?) observability tests are pinned to 2.9.29 because of https://bugs.launchpad.net/juju/+bug/1977582, so only if 2.9.33 fixes it we would unpin.

BTW would it be easy for pylibjuju to raise a runtime error if the controller version is too old?

**Comment by juanmanuel-tirado** [comment]
We have not decided so far the list of Juju controllers to be supported by every pylibjuju version. But that makes perfect sense.

**Pull request merged**
